version: '3.12'

services:
  chat_api:
    build: 
      dockerfile: Dockerfile
      context: ./chat-api
      target: development

    volumes:
      - ./chat-api:/habberrih/src/app
      - /habberrih/src/app/node_modules
    
    command: npm run start:dev

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://user:password@chat_db:5432/chat
      NODE_ENV: development
      PORT: 3000

    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development

    command: npm run start
    volumes:
      - ./frontend:/habberrih/frontend/src/app
      - /habberrih/frontend/src/app/node_modules

    ports:
      - 4200:4200

    links:
     - chat_api
  
  postgres:
    image: postgres:15.2-alpine
    
    container_name: chat_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432

  postgres_admin:
    image: dpage/pgadmin4:latest
    
    depends_on:
      - postgres
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - 5050:80


volumes:
  postgres-db:
    driver: local